version: '3.3'

services:
  db:
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: salesio
      MYSQL_DATABASE: salesio
      MYSQL_USER: salesio
      MYSQL_PASSWORD: salesio
volumes:
  db_data: {}
